#!/bin/bash
clear 
. config

# Select the date for which we'll be copying video files.

PS3='For which day?'
day=("Today" "Yesterday" "2 Days Ago" "3 Days Ago" "4 Days Ago") # Options
select option1 in "${day[@]}"; do
    case $option1 in
        "Today")
            date=$(date +"%Y-%m-%d")
            echo $date
            break
        ;;
        "Yesterday")
            date=$(date -v -1d +"%Y-%m-%d")
            echo $date
            break
        ;;
        "2 Days Ago")
            date=$(date -v -2d +"%Y-%m-%d")
            echo $date
            break
        ;;
        "3 Days Ago")
            date=$(date -v -3d +"%Y-%m-%d")
            echo $date
            break
        ;;
        "4 Days Ago")
            date=$(date -v -4d +"%Y-%m-%d")
            echo $date
            break
        ;;
    esac
done

# Define target folder for copying files
destination="$copy_to_path/$date" # Target folder

# Check to see if target folder already exists so we don't attempt to create it again
if [ -d "$destination" ]
then
    echo "Folder already exists for $date"
else
    echo "Folder does not exist"
    echo "Creating Folder"
    mkdir $copy_to_path/$date
fi

copy_files () {
    
    echo "You chose $option2."
    if [ -d "$destination/$option2" ] # Check to see if camera subdirectory already exists on target.
    then
    echo "Camera folder already exists"
    exit
    else
    mkdir "$destination/$option2" # Create camera folder if it doesn't exist.
    
    # Use find to generate a list of all mp4 files under the ZM folder structure.
    find $zm_event_path/$1/$date -name \*.mp4 > "$destination/$option2/list.txt"
    
    # Use rsync to copy those files from the source to the target.
    rsync -azvp --no-relative --progress --files-from="$destination/$option2/list.txt" / "/Volumes/SpeedyG/Movies/$date/$option2/"
    fi 

}

# Select which files we'll be copying by camera name
PS3='Which ZoneMinder camera?'
cameras=("$cam1" "$cam3" "$cam2" "Quit") # Options
select option2 in "${cameras[@]}"; do
    case $option2 in
        "$cam1")
            copy_files "1"
            ;;
        "$cam3")
            copy_files "3"
            ;;
        "$cam2")
            copy_files "2"
            ;;
        "Quit")
            echo "User requested exit"
            exit
            ;;
        *) echo "Invalid option $REPLY";;
    esac
done
